### ISSUE TITLE
Use convencional commits messages

### ISSUE THREAD

**Issue by TyperGuy** [ElianaNeto/CRUD-FLASK#1]
Dear Eliana, i hope you´re good
Firstly i want to congrats you to estart a new journey of study.

I higly recomend you to use a commit message pattern, it helps others programmers to understand more better whtas you are commiting or pushing up to your repository. It also help those who wants to help you to solve some kind of problem in your code.

If you are interested, check out the "Convencional Commits " pattern documentation  https://www.conventionalcommits.org/en/v1.0.0/

**Comment by ElianaNeto** [comment]
Hi @TyperGuy , sorry for the delay and thanks for the tip. 👍🏿 I will try and put it into practice. Hugs ❤️
